# Generated by Django 2.1.5 on 2019-01-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del usuario')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos del usuario')),
                ('balance', models.IntegerField(verbose_name='Dinero en la cuenta')),
            ],
        ),
    ]
